package builder

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/ChristianKreuzberger/press/internal/page"
)

var errUnsafeOutputDir = errors.New("refusing to use output directory")

var errNotPressOutput = errors.New("not press output")

// outputMarker is written into every output dir press builds. A non-empty
// directory is only ever emptied if it carries this marker (or, for dist/
// folders made by older press versions, looks like press output).
const outputMarker = ".press-output"

// checkOutputDir decides whether outputDir may be emptied: a non-empty dir must
// be recognisably press output. Build runs validateOutputDir (source overlap)
// before this. It has no side effects, so Build can run it before creating
// anything. It returns the resolved output path.
func checkOutputDir(siteDir, outputDir, staticDir string) (string, error) {
	out, err := resolvePath(outputDir)
	if err != nil {
		return "", fmt.Errorf("resolving output dir: %w", err)
	}
	if err := checkOwnership(siteDir, out, outputDir, staticDir); err != nil {
		return "", err
	}
	return out, nil
}

// checkOwnership allows a missing dir, an empty dir, a dir with the marker, or
// an unmarked dir that looks like output of an older press version.
func checkOwnership(siteDir, out, outputDir, staticDir string) error {
	info, err := os.Stat(out)
	if errors.Is(err, fs.ErrNotExist) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("reading output directory: %w", err)
	}
	if !info.IsDir() {
		return fmt.Errorf("%w %s: not a directory", errUnsafeOutputDir, outputDir)
	}
	entries, err := os.ReadDir(out)
	if err != nil {
		return fmt.Errorf("reading output directory: %w", err)
	}
	if len(entries) == 0 {
		return nil
	}
	if fi, err := os.Lstat(filepath.Join(out, outputMarker)); err == nil && fi.Mode().IsRegular() {
		return nil
	}
	if looksLikeLegacyOutput(siteDir, out, staticDir) {
		return nil
	}
	return fmt.Errorf("%w %s: it is not empty and was not created by press (no %s file). "+
		"Use an empty or new directory, or delete it yourself first", errUnsafeOutputDir, outputDir, outputMarker)
}

// looksLikeLegacyOutput reports whether every file in out is something press
// would have written before markers existed: a .html file, or a file that also
// exists in pages/ or the static dir at the same relative path. Symlinks and
// anything else (a .git dir, a README, notes) make it "not ours".
func looksLikeLegacyOutput(siteDir, out, staticDir string) bool {
	roots := []string{page.PagesDir(siteDir), filepath.Join(siteDir, staticDir)}
	err := filepath.WalkDir(out, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		if !d.Type().IsRegular() {
			return errNotPressOutput
		}
		if strings.HasSuffix(d.Name(), ".html") {
			return nil
		}
		rel, err := filepath.Rel(out, p)
		if err != nil {
			return err
		}
		for _, r := range roots {
			if fi, err := os.Lstat(filepath.Join(r, rel)); err == nil && fi.Mode().IsRegular() {
				return nil
			}
		}
		return errNotPressOutput
	})
	return err == nil
}

// stagingPath and previousPath are hidden siblings of out, on the same
// filesystem so a rename between them is atomic. The names are fixed so a crash
// leaves at most one of each, which the next build removes.
func stagingPath(out string) string {
	return filepath.Join(filepath.Dir(out), "."+filepath.Base(out)+".press-new")
}
func previousPath(out string) string {
	return filepath.Join(filepath.Dir(out), "."+filepath.Base(out)+".press-old")
}

// prepareStaging creates an empty, marked staging dir next to out (already
// validated by checkOutputDir), after removing leftovers of a crashed build. A
// leftover is only removed if it is empty or carries the marker, so an unrelated
// dir that happens to have the reserved name is never deleted.
func prepareStaging(out string) (string, error) {
	if err := os.MkdirAll(filepath.Dir(out), 0755); err != nil { //nolint:gosec // generated site output must be world-readable for web servers
		return "", fmt.Errorf("creating output directory: %w", err)
	}
	staging := stagingPath(out)
	for _, p := range []string{staging, previousPath(out)} {
		if err := removeIfPressOwned(p); err != nil {
			return "", err
		}
	}
	if err := os.Mkdir(staging, 0755); err != nil { //nolint:gosec // generated site output must be world-readable for web servers
		return "", fmt.Errorf("creating staging directory: %w", err)
	}
	if err := os.WriteFile(filepath.Join(staging, outputMarker), []byte("generated by press; safe to delete\n"), 0644); err != nil { //nolint:gosec // output must be world-readable
		return "", fmt.Errorf("writing output marker: %w", err)
	}
	return staging, nil
}

// removeIfPressOwned removes a leftover staging dir; it refuses anything that is
// not an empty or marked directory.
func removeIfPressOwned(path string) error {
	fi, err := os.Lstat(path)
	if errors.Is(err, fs.ErrNotExist) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("reading %s: %w", path, err)
	}
	if fi.IsDir() {
		entries, err := os.ReadDir(path)
		if err != nil {
			return fmt.Errorf("reading %s: %w", path, err)
		}
		if mfi, err := os.Lstat(filepath.Join(path, outputMarker)); len(entries) == 0 || (err == nil && mfi.Mode().IsRegular()) {
			return os.RemoveAll(path)
		}
	}
	return fmt.Errorf("%w: %s already exists and was not created by press. Delete or rename it", errUnsafeOutputDir, path)
}

// swapOutput replaces out (already validated by checkOutputDir) with staging, so
// the output is either the complete previous site or the complete new one, and a
// failed build never touches it. It takes two renames, so a request that lands
// between them can briefly get a 404; if the second fails the first is undone.
// A failing rename (an output dir that is a mount point, or open files on
// Windows) is reported, and the previous output is left in place.
func swapOutput(staging, out string) error {
	if _, err := os.Lstat(out); errors.Is(err, fs.ErrNotExist) {
		if err := os.Rename(staging, out); err != nil {
			return fmt.Errorf("moving new output into place: %w", err)
		}
		return nil
	}
	previous := previousPath(out)
	if err := os.Rename(out, previous); err != nil {
		return fmt.Errorf("replacing output directory %s (is it a mount point or in use by another program?): %w", out, err)
	}
	if err := os.Rename(staging, out); err != nil {
		if rerr := os.Rename(previous, out); rerr != nil {
			return fmt.Errorf("moving new output into place: %w (and restoring the previous output failed: %v; it is in %s)", err, rerr, previous)
		}
		return fmt.Errorf("moving new output into place: %w", err)
	}
	// Best effort: a leftover is marked, so the next build removes it.
	_ = os.RemoveAll(previous)
	return nil
}
